### ISSUE TITLE
Error: Process completed with exit code 123

### ISSUE THREAD

**Issue by ngljcb** [csunibo/ipim-ingegneria-del-software#17]
ciao ragazzi,
qualcuno può aiutarmi a capire perche mi ha dato questo errore del build&deploy di una risorsa (pdf) del pr #16 .
suppongo che non c'entra il file che sto caricando (file pdf), ma probabilmente da un file già presente nel repo.

qualcuno può dare un occhiata please?
grazie mille

**Comment by samuelemusiani** [comment]
Risolto :)

**Comment by ngljcb** [comment]
grazie mille!! :)
